# Site
name: "The Droid Zone"
title: "The Droid Zone"
beta: false
description: "Random thoughts, musings, and things Droid"
meta_description: "Android development, Kotlin, Deep Thoughts, and Musings"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: 'ntxdroid.com'
email: 'ntxdroid@gmail.com'
google_analytics: ''
disqus: 'ntxdroid'
sharethis: ''
include: ["_pages"]

# Authors
authors:
  al:
    name: Al
    display_name: Al
    gravatar: 9aece350f7fe51308e19b3b693a77a8a
    email: ntxdroid@gmail.com
    web: https://ntxdroid.com/
    twitter:
    description: "Retired programmer keeping a sharp mind by doing it for fun instead of a paycheck. Never stop learning."
  sal:
    name: Sal
    display_name: Sal
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/wowthemesnet
    description: "Author of Affiliates, a template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  john:
    name: John
    display_name: John
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

feed:
  path: atom.xml

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Other
markdown: kramdown
highlighter: rouge
